Repository taranis-ai/taranis-ai, pull requests merged in 2025-08, with the labels that each got.

#587 Remove dropdown from tag combobox
  src/core/tests/playwright/test_e2e_user.py
  src/gui/src/components/assess/EditTags.vue
Labels: bug

#597 Fix test_e2e_publish rendering
  src/core/tests/playwright/conftest.py
  src/core/tests/playwright/test_e2e_user.py
  src/core/tests/playwright/test_e2e_workflow.py
  src/gui/src/components/publish/ProductItem.vue
Labels: bug

#599 Force submission of falsy form_switches in frontend
  src/frontend/frontend/templates/macros/forms.html
  src/frontend/frontend/templates/partials/worker_parameters.html
Labels: bug, frontend

#600 Feature/global collector proxy
  src/core/core/api/worker.py
  src/core/core/managers/pre_seed_data.py
  src/core/core/model/osint_source.py
  src/core/tests/functional/test_worker.py
Labels: enhancement

#570 Fix/show collector not modified
  src/core/core/api/task.py
  src/core/core/api/worker.py
  src/core/core/model/osint_source.py
  src/frontend/frontend/filters.py
  src/frontend/frontend/templates/osint_source/osint_source_form.html
  src/frontend/frontend/templates/partials/state_badge.html
  src/frontend/uv.lock
  src/models/models/types.py
  src/worker/worker/collectors/collector_tasks.py
  src/worker/worker/collectors/rss_collector.py
  src/worker/worker/collectors/rt_collector.py
  src/worker/worker/collectors/simple_web_collector.py
  src/worker/worker/collectors/twitter_collector.py
  src/worker/worker/core_api.py
  src/worker/worker/tests/collectors/test_collector.py
Labels: bug

#645 Make NLP bot do tag updates in batches
  src/worker/worker/bots/nlp_bot.py
  src/worker/worker/tests/bots/test_bots.py
Labels: enhancement
